# Generated by Django 5.1.1 on 2024-09-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HousePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detached_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('semi_detached_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('terraced_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flat_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
